apiVersion: v1
kind: Service
metadata:
  name: frontend-deployment
  namespace: three-tier-app
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    app: frontend-deployment